[package]
name = "bevy-game-jam"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6.0"
rand = "0.7.3"

[workspace]
resolver = "2" # Important! wgpu/Bevy needs this!
